# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C-5T5UAPaSss7jDmI1xRSAxuDAN-QOQF
"""

pip install streamlit

import streamlit as st
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer

#load save model
model=pickle.load(open('Tweetstem2.sav','rb'))

tfidf=TfidfVectorizer
loaded_vec=TfidfVectorizer(decode_error='replace', vocabulary=set(pickle.load(open('Fitur_baru_TFIDF.sav','rb'))))

#judul halaman
st.title('Prediksi Berita')

clean_teks=st.text_input('Masukkan Berita')
data_deteksi = ''

if st.button('Hasil Deteksi'):
    predict_berita = model.predict(loaded_vec.fit_transform([clean_teks]))

    if(predict_berita==0):
        data_deteksi='Berita Fake'
    else:
        data_deteksi='Berita Real'
st.success(data_deteksi)

